spring:
  datasource:
    url: jdbc:mysql://localhost:3306/krusty-krab?useSSL=false
    username: root
    password: MyNewPass
    driver-class-name: com.mysql.cj.jdbc.Driver
    security:
      oauth2:
        client:
          registration:
            github:
              clientId: 94de119da4ba1ac744a5
              clientSecret: 939512160a69b83fcc6b6bbfb1cbbab1727476b5
    # ...


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 7000
